plugins {
    id 'java'
    id 'maven-publish'
    id 'org.springframework.boot' version '3.5.16'
    id 'war'
}

repositories {
    mavenLocal()
    mavenCentral()
//    jcenter()
//    maven {
//        url = 'https://builds.archive.org/maven2'
//    }
    
    maven {
        url = 'https://repo.maven.apache.org/maven2'
    }

    maven{
        url = 'https://repository.cloudera.com/artifactory/libs-release-local/'
    }
}

dependencies {
    // This artifact no longer exists in public repos and we don't seem to need it
    //implementation 'com.sun.jmx:jmxri:1.2.1'
    implementation 'log4j:log4j:1.2.17'
    implementation 'org.quartz-scheduler:quartz:2.3.1'
    implementation 'com.sun.xml.bind:jaxb-impl:2.3.2'
    implementation 'com.sun.xml.bind:jaxb-core:2.3.0'
    implementation 'javax.xml.bind:jaxb-api:2.3.0'
    implementation 'org.webcurator:webcurator-core:3.2.5-SNAPSHOT'
    implementation 'org.netarchivesuite:heritrix3-wrapper:1.0.3'
    testImplementation 'junit:junit:4.12'
    testImplementation 'org.mockito:mockito-core:1.9.5'
// https://mvnrepository.com/artifact/org.seleniumhq.webdriver/webdriver-selenium
    implementation group: 'org.seleniumhq.webdriver', name: 'webdriver-selenium', version: '0.9.7376'
// https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-api
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-api', version: '3.141.59'
// https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-chrome-driver
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-chrome-driver', version: '3.141.59'
// https://mvnrepository.com/artifact/org.seleniumhq.selenium/selenium-support
    implementation group: 'org.seleniumhq.selenium', name: 'selenium-support', version: '3.141.59'
// https://mvnrepository.com/artifact/ru.yandex.qatools.ashot/ashot
    implementation group: 'ru.yandex.qatools.ashot', name: 'ashot', version: '1.5.4'
}

group = 'org.webcurator'
version = '3.2.5-SNAPSHOT'
description = 'Harvest Agent - Heritrix 3.x'

java {
	sourceCompatibility = '1.8'
	targetCompatibility = '1.25'
}

task sourcesJar(type: Jar) {
    archiveClassifier.set('sources')
    from(sourceSets.main.allJava)
}

// just an alias
task install(dependsOn: ['bootJar', 'publishToMavenLocal'])

jar {
    enabled = true
}

bootJar {
    archiveClassifier = 'application'
}

publishing {
    publications {
        maven(MavenPublication) {
            from(components.java)
            artifact(sourcesJar) 
        }
    }
}

tasks.withType(JavaCompile) {
    options.encoding = 'UTF-8'
}
