-- Create a view to speed up the targets query of rest api
DROP VIEW IF EXISTS DB_WCT.ABSTRACT_TARGET_SUMMARY_VIEW;
CREATE VIEW DB_WCT.ABSTRACT_TARGET_SUMMARY_VIEW AS
SELECT 	ABSTRACT_TARGET.AT_OID,
		ABSTRACT_TARGET.AT_NAME,
		ABSTRACT_TARGET.AT_DESC,
		ABSTRACT_TARGET.AT_STATE,
		ABSTRACT_TARGET.AT_CREATION_DATE,
		ABSTRACT_TARGET.AT_DISPLAY_TARGET,
		WCTUSER.USR_OID,
		WCTUSER.USR_USERNAME,
		WCTUSER.USR_FIRSTNAME,
		WCTUSER.USR_LASTNAME,
		AGENCY.AGC_OID,
		AGENCY.AGC_NAME,
		SEEDS.SEED_IDS,
		SEEDS.SEED_NAMES,
		SEEDS.SEED_PRIMARIES,
		TARGET_GROUPS.GROUP_NAMES
FROM   	DB_WCT.TARGET
INNER JOIN DB_WCT.ABSTRACT_TARGET
	ON ABSTRACT_TARGET.AT_OID = TARGET.T_AT_OID
INNER JOIN DB_WCT.WCTUSER
    ON ABSTRACT_TARGET.AT_OWNER_ID = WCTUSER.USR_OID
INNER JOIN DB_WCT.AGENCY
    ON WCTUSER.USR_AGC_OID = AGENCY.AGC_OID
LEFT JOIN 	(SELECT S_TARGET_ID,
	                STRING_AGG(CAST(S_OID AS TEXT), ',') AS SEED_IDS,
	                STRING_AGG(S_SEED, ',') AS SEED_NAMES,
	                STRING_AGG(CAST(CAST(S_PRIMARY AS INTEGER) AS TEXT), ',') AS SEED_PRIMARIES
	        FROM   DB_WCT.SEED
	        GROUP  BY S_TARGET_ID) SEEDS
    ON ABSTRACT_TARGET.AT_OID = SEEDS.S_TARGET_ID
LEFT JOIN (SELECT 	GROUP_MEMBER.GM_CHILD_ID AS TARGET_ID,
					STRING_AGG(ABSTRACT_TARGET.AT_NAME, ',') AS GROUP_NAMES
			FROM 	DB_WCT.GROUP_MEMBER
			INNER JOIN DB_WCT.ABSTRACT_TARGET
			        ON GROUP_MEMBER.GM_PARENT_ID = ABSTRACT_TARGET.AT_OID
			GROUP BY GROUP_MEMBER.GM_CHILD_ID
			) TARGET_GROUPS
	ON TARGET.T_AT_OID = TARGET_GROUPS.TARGET_ID;

GRANT SELECT, INSERT, UPDATE, DELETE ON DB_WCT.ABSTRACT_TARGET_SUMMARY_VIEW TO USR_WCT;
