/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('openvue/badge')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    Button: typeof import('openvue/button')['default']
    Card: typeof import('openvue/card')['default']
    Checkbox: typeof import('openvue/checkbox')['default']
    Chip: typeof import('openvue/chip')['default']
    Column: typeof import('openvue/column')['default']
    ConfirmDialog: typeof import('openvue/confirmdialog')['default']
    DataTable: typeof import('openvue/datatable')['default']
    DatePicker: typeof import('openvue/datepicker')['default']
    Divider: typeof import('openvue/divider')['default']
    DynamicDialog: typeof import('openvue/dynamicdialog')['default']
    Fluid: typeof import('openvue/fluid')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconInfo: typeof import('./src/components/icons/IconInfo.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconWarning: typeof import('./src/components/icons/IconWarning.vue')['default']
    InputGroup: typeof import('openvue/inputgroup')['default']
    InputGroupAddon: typeof import('openvue/inputgroupaddon')['default']
    InputNumber: typeof import('openvue/inputnumber')['default']
    InputText: typeof import('openvue/inputtext')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Message: typeof import('openvue/message')['default']
    MultiSelect: typeof import('openvue/multiselect')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Paginator: typeof import('openvue/paginator')['default']
    Panel: typeof import('openvue/panel')['default']
    ProgressSpinner: typeof import('openvue/progressspinner')['default']
    RadioButton: typeof import('openvue/radiobutton')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('openvue/select')['default']
    Tab: typeof import('openvue/tab')['default']
    TabList: typeof import('openvue/tablist')['default']
    TabPanel: typeof import('openvue/tabpanel')['default']
    TabPanels: typeof import('openvue/tabpanels')['default']
    Tabs: typeof import('openvue/tabs')['default']
    Textarea: typeof import('openvue/textarea')['default']
    Timeline: typeof import('openvue/timeline')['default']
    Toast: typeof import('openvue/toast')['default']
    ToggleSwitch: typeof import('openvue/toggleswitch')['default']
    WctFormField: typeof import('./src/components/WctFormField.vue')['default']
    WctPrimaryButton: typeof import('./src/components/WctPrimaryButton.vue')['default']
    WctSearchField: typeof import('./src/components/WctSearchField.vue')['default']
    WctTabViewPanel: typeof import('./src/components/WctTabViewPanel.vue')['default']
    WctTopLabel: typeof import('./src/components/WctTopLabel.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('openvue/tooltip')['default']
  }
}
