/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Badge: typeof import('./src/components/Badge.vue')['default']
    BlockViewer: typeof import('./src/components/BlockViewer.vue')['default']
    Button: typeof import('./src/components/Button.vue')['default']
    Card: typeof import('./src/components/Card.vue')['default']
    Checkbox: typeof import('./src/components/Checkbox.vue')['default']
    Chip: typeof import('./src/components/Chip.vue')['default']
    Column: typeof import('./src/components/Column.vue')['default']
    ConfirmDialog: typeof import('./src/components/ConfirmDialog.vue')['default']
    DataTable: typeof import('./src/components/DataTable.vue')['default']
    DatePicker: typeof import('./src/components/DatePicker.vue')['default']
    Divider: typeof import('./src/components/Divider.vue')['default']
    DynamicDialog: typeof import('./src/components/DynamicDialog.vue')['default']
    Fluid: typeof import('./src/components/Fluid.vue')['default']
    IconCommunity: typeof import('./src/components/icons/IconCommunity.vue')['default']
    IconDocumentation: typeof import('./src/components/icons/IconDocumentation.vue')['default']
    IconEcosystem: typeof import('./src/components/icons/IconEcosystem.vue')['default']
    IconInfo: typeof import('./src/components/icons/IconInfo.vue')['default']
    IconSupport: typeof import('./src/components/icons/IconSupport.vue')['default']
    IconTooling: typeof import('./src/components/icons/IconTooling.vue')['default']
    IconWarning: typeof import('./src/components/icons/IconWarning.vue')['default']
    InputGroup: typeof import('./src/components/InputGroup.vue')['default']
    InputGroupAddon: typeof import('./src/components/InputGroupAddon.vue')['default']
    InputNumber: typeof import('./src/components/InputNumber.vue')['default']
    InputText: typeof import('./src/components/InputText.vue')['default']
    Loading: typeof import('./src/components/Loading.vue')['default']
    Message: typeof import('./src/components/Message.vue')['default']
    MultiSelect: typeof import('./src/components/MultiSelect.vue')['default']
    NavBar: typeof import('./src/components/NavBar.vue')['default']
    Paginator: typeof import('./src/components/Paginator.vue')['default']
    Panel: typeof import('./src/components/Panel.vue')['default']
    ProgressSpinner: typeof import('./src/components/ProgressSpinner.vue')['default']
    RadioButton: typeof import('./src/components/RadioButton.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('./src/components/Select.vue')['default']
    Tab: typeof import('./src/components/Tab.vue')['default']
    TabList: typeof import('./src/components/TabList.vue')['default']
    TabPanel: typeof import('./src/components/TabPanel.vue')['default']
    TabPanels: typeof import('./src/components/TabPanels.vue')['default']
    Tabs: typeof import('./src/components/Tabs.vue')['default']
    Textarea: typeof import('./src/components/Textarea.vue')['default']
    Timeline: typeof import('./src/components/Timeline.vue')['default']
    Toast: typeof import('./src/components/Toast.vue')['default']
    ToggleSwitch: typeof import('./src/components/ToggleSwitch.vue')['default']
    WctFormField: typeof import('./src/components/WctFormField.vue')['default']
    WctPrimaryButton: typeof import('./src/components/WctPrimaryButton.vue')['default']
    WctSearchField: typeof import('./src/components/WctSearchField.vue')['default']
    WctTabViewPanel: typeof import('./src/components/WctTabViewPanel.vue')['default']
    WctTopLabel: typeof import('./src/components/WctTopLabel.vue')['default']
  }
}
